dist: xenial
language: python
python:
  - "3.9"

env:
  global:
    - JUNIT_FILE_PATH="reports/junit-report.xml"

before_install:
  - python -m venv venv
  - source venv/bin/activate
  - sudo apt-get update
  - sudo apt-get install -y curl

install:
  - cd samples/python/pytest
  - echo "Listing files in the current directory:"
  - ls -l
  - if [ -f "requirements.txt" ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi

script:
  - pytest --junitxml=reports/junit-report.xml ./tests || true
  - echo "JUnit report generated:"
  - ls -l reports/

after_script:
  - |
    echo "Current working directory:"
    pwd
    echo "Listing files in the reports directory:"
    ls -l reports/ || echo "Reports directory not found"
    echo "Checking if JUnit report file exists at $JUNIT_FILE_PATH"
    if [ -f "$JUNIT_FILE_PATH" ]; then
      echo "JUnit report file found: $JUNIT_FILE_PATH"
      CURL_COMMAND="curl -X POST $API_URL -H \"x-api-key: $API_KEY\" -F \"file=@$JUNIT_FILE_PATH\""
      echo "Executing curl command: $CURL_COMMAND"
      RESPONSE=$(eval $CURL_COMMAND)
      echo "API Response:"
      echo "$RESPONSE"
    else
      echo "JUnit report file not found: $JUNIT_FILE_PATH"
      exit 1
    fi
