trigger:
  - sampleCode

pool:
  vmImage: ubuntu-latest

variables:
  - group: testrun

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Setup Python'

  - script: |
      cd samples/python/pytest
      pip install -r requirements.txt || true
      pytest --junitxml "reports/junit-report.xml" "./tests" || true
    displayName: 'Run pytest tests'
    continueOnError: true

  - script: |
      echo "Current working directory:"
      pwd
      echo "Listing files in the reports directory:"
      ls -l reports/ || echo "Reports directory not found"
      echo "API_URL is $API_URL"
      echo "API_KEY is $API_KEY"
      echo "Checking if JUnit report file exists at $JUNIT_FILE_PATH"
      if [ -f "$JUNIT_FILE_PATH" ]; then
        echo "JUnit report file found: $JUNIT_FILE_PATH"
        CURL_COMMAND="curl -X POST $API_URL -H \"x-api-key: $API_KEY\" -F \"file=@$JUNIT_FILE_PATH\""
        echo "Executing curl command: $CURL_COMMAND"
        RESPONSE=$(eval $CURL_COMMAND)
        echo "API Response:"
        echo "$RESPONSE"
      else
        echo "JUnit report file not found: $JUNIT_FILE_PATH"
        exit 1
      fi
    displayName: 'Upload Pytest Results to Backend'
    env:
      JUNIT_FILE_PATH: "samples/python/pytest/reports/junit-report.xml"
      API_URL: $(API_URL)
      API_KEY: $(API_KEY)