version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout

  setup-venv:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Setup virtual environment
          command: |
            cd samples/python/pytest
            python -m venv ./venv

  execute-tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Execute automated tests
          command: |
            cd samples/python/pytest
            . ./venv/bin/activate
            pip install -r requirements.txt
            pytest --junitxml=reports/junit-report.xml ./tests || true
            echo "JUnit report generated:"
            ls -l reports/

  post-results:
    docker:
      - image: circleci/python:3.10
    environment:
      API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IjE2ODdiMTE1LWE0MzItNDQyZC1iYzAwLWQ4MzU5Mzk1NzAyOSIsInVzZXJJZCI6ImNlZTA5ZDQyLTA2YzMtNDU5OS1hODZlLTg2YzgwMTM4ZGNiOSIsImlhdCI6MTcyMTEyNjA3OH0.tRsXbvHXgXSlnRGCSiS_pDvxS5BrqH_i_WCpV4GCgaI"
      API_URL: "http://localhost:3000/api/projects/integration/jenkins/result/beeeb35d-1633-4ac1-a16c-a459a2d7b302"
    steps:
      - checkout
      - run:
          name: Post results
          command: |
            cd samples/python/pytest
            junitFilePath="reports/junit-report.xml"
            
            if [ -f "${junitFilePath}" ]; then
                echo "JUnit report file found: ${junitFilePath}"
                
                response=$(curl -X POST ${API_URL} \
                  -H "x-api-key: ${API_KEY}" \
                  -F "file=@${junitFilePath}")

                echo "API Response:"
                echo "${response}"
                
            else
                echo "JUnit report file not found: ${junitFilePath}"
                exit 1
            fi

workflows:
  version: 2
  sample:
    jobs:
      - checkout
      - setup-venv:
          requires:
            - checkout
      - execute-tests:
          requires:
            - setup-venv
      - post-results:
          requires:
            - execute-tests
