version: 2.1
working_directory: ~/automation-framework-integration
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout  # Perform code checkout
      - run:
          name: Set up virtual environment
          command: |
            cd samples/python/pytest
            python -m venv ./venv
      - run:
          name: Install dependencies
          command: |
            cd samples/python/pytest
            . ./venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Build and run the tests
          command: |
            cd samples/python/pytest
            . ./venv/bin/activate
            pytest --junitxml=reports/junit-report.xml ./tests || true
            echo "JUnit report generated:"
            ls -l reports/
      - persist_to_workspace:
          root: samples/python/pytest
          paths:
            - reports/junit-report.xml
  post-results:
    docker:
      - image: circleci/python:3.10
    steps:
      - attach_workspace:
          at: ./samples/python/pytest
      - run:
          name: Post JUnit results to API
          command: |
            JUNIT_FILE_PATH="samples/python/pytest/reports/junit-report.xml"
            API_URL="https://5fd6-157-42-204-230.ngrok-free.app/api/projects/integration/circleci/result/beeeb35d-1633-4ac1-a16c-a459a2d7b302"
            
            # API_URL="http://localhost:3000/api/projects/integration/circleci/result/beeeb35d-1633-4ac1-a16c-a459a2d7b302"
            API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IjE2ODdiMTE1LWE0MzItNDQyZC1iYzAwLWQ4MzU5Mzk1NzAyOSIsInVzZXJJZCI6ImNlZTA5ZDQyLTA2YzMtNDU5OS1hODZlLTg2YzgwMTM4ZGNiOSIsImlhdCI6MTcyMTEyNjA3OH0.tRsXbvHXgXSlnRGCSiS_pDvxS5BrqH_i_WCpV4GCgaI"
            if [ -f "$JUNIT_FILE_PATH" ]; then
              echo "JUnit report file found: $JUNIT_FILE_PATH"
              CURL_COMMAND="curl -X POST $API_URL -H \"x-api-key: $API_KEY\" -F \"file=@$JUNIT_FILE_PATH\""
              echo "Executing curl command: $CURL_COMMAND"
              RESPONSE=$(eval $CURL_COMMAND)
              echo "API Response:"
              echo "$RESPONSE"
            else
              echo "JUnit report file not found: $JUNIT_FILE_PATH"
              exit 1
            fi

workflows:
  sample:
    jobs:
      - build-and-test
      - post-results:
          requires:
            - build-and-test
