version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
working_directory: ~/automation-framework-integration
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 109.0.5414.74
      - checkout  # Performs code checkout
      - run:
          name: Build and run the tests
          command: |
            chmod 777 drivers/linux/chromedriver
            mvn clean compile test
      - persist_to_workspace:
          root: ./
          paths:
            - target/TEST-junit-jupiter.xml
  post-results:
    docker:
      - image: cimg/python:3.11
    steps:
     - attach_workspace:
         at: ./automation-framework-integration
     - run:
         name: Post JUnit results to API
         command: |
           JUNIT_FILE_PATH="./automation-framework-integration/target/TEST-junit-jupiter.xml"
           API_URL="http://localhost:3000/api/projects/integration/jenkins/result/beeeb35d-1633-4ac1-a16c-a459a2d7b302"
           API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IjE2ODdiMTE1LWE0MzItNDQyZC1iYzAwLWQ4MzU5Mzk1NzAyOSIsInVzZXJJZCI6ImNlZTA5ZDQyLTA2YzMtNDU5OS1hODZlLTg2YzgwMTM4ZGNiOSIsImlhdCI6MTcyMTEyNjA3OH0.tRsXbvHXgXSlnRGCSiS_pDvxS5BrqH_i_WCpV4GCgaI"
           if [ -f "$JUNIT_FILE_PATH" ]; then
             echo "JUnit report file found: $JUNIT_FILE_PATH"
             curl -X POST $API_URL \
               -H "x-api-key: $API_KEY" \
               -F "file=@$JUNIT_FILE_PATH"
           else
             echo "JUnit report file not found: $JUNIT_FILE_PATH"
             exit 1
           fi

workflows:
  sample:
    jobs:
      - build-and-test
      - post-results:
          requires:
            - build-and-test
